name: Build and Deploy app.yml on main

on:
  push:
    branches:
      - main
    paths:
      - 'メニュー/**.xlsx'
  pull_request:
    branches:
      - main
    paths:
      - 'メニュー/**.xlsx'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Convert Excel to app.yml
        run: |
          node bin/xlsx2json.js ./メニュー/メニュー.xlsx 
          node ./bin/configToMenuYAML.js data.json ./app.yml

      - name: Configure AWS Credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302263045312:role/dev-maps-yaizu-smartcity-jp-github-actions-deploy-dev
          aws-region: ap-northeast-1
  
      - name: Deploy to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws s3 sync ./dist s3://dev-maps-yaizu-smartcity-jp-frontend-dev \
            --delete \
            --cache-control "public,max-age=60" \
            --exclude "app.yml"
          
          aws cloudfront create-invalidation --distribution-id "EFX61YORGLNRP" --paths "/*"