name: ⚠️スマートマップを本番にデプロイ
on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  deploy-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302263045312:role/dev-maps-yaizu-smartcity-jp-github-actions-deploy-dev
          aws-region: ap-northeast-1

      - name: app.ymlを開発環境からダウンロード
        run: |
          aws s3 cp s3://dev-maps-yaizu-smartcity-jp-frontend-dev/app.yml ./app.yml


      - name: Configure AWS Credentials
        if : github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302263045312:role/maps-yaizu-smartcity-jp-github-actions-deploy-v1
          aws-region: ap-northeast-1
          
      - name: app.ymlを本番環境にコピー
        run: |
          aws s3 cp ./app.yml s3://maps-yaizu-smartcity-jp-frontend-v1/app.yml

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id "E2RMR3GLW2EGUT" --paths "/app.yml"
